version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - DB_URL=mongodb://host.docker.internal:27017/jobgo
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      # Keep other envs from .env file or override here if needed
    env_file:
      - ./backend/.env
    depends_on:
      # - mongo
      - redis
      - elasticsearch
    volumes:
      - ./backend:/app
      - /app/node_modules
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # mongo:
  #   image: mongo:latest
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo_data:/data/db
 
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    environment:
      - cluster.name=jobgo-cluster
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch

volumes:
  mongo_data:
  es_data:
